### ISSUE TITLE
Failing tests when running in browsers

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#508]
The error appearing when running tests from current `master` is: 

```
TypeError: 'undefined' is not a function (evaluating 'sinon.useFakeXMLHttpRequest()')
at Object.sinon.fakeServer.create (http://localhost:8123/lib/sinon/util/fake_server.js:82:30)
```

If my use of `git bisect` is correct, then c28f47f917984167c88e24b04f6aa400654cf749 is the first commit where the tests fail when run in a browser.

**NOTE:** You will need to run the tests from the test page served from a webserver, and not just loaded from the file system, or you will get other errors as well, making it more difficult to isolate this issue.
