### ISSUE TITLE
sinon-test is broken when using sinon v17.0.2

### ISSUE THREAD

**Issue by john-mills-nz** [sinonjs/sinon#2597]
**Describe the bug**
After upgrading sinon to v17.0.2 sinon-test stops working. The error `TypeError: this.stub is not a function` occurs. Reverting to v17.0.1 fixes it.

**To Reproduce**

1. Update to v17.0.2
2. Run tests
3. See error

- Sinon version : v17.0.2

- Other libraries you are using:
   - sinon-test

**Comment by fatso83** [comment]
[This is fixed in sinon-test 3.1.6](https://github.com/sinonjs/sinon-test/blob/main/History.md#316--2024-05-15) in commit https://github.com/sinonjs/sinon-test/commit/cd5164987d3705208bebee1b291797d87b090220
