### ISSUE TITLE
Migrating to 2.0: Issue with stub with sandbox

### ISSUE THREAD

**Issue by gyandeeps** [sinonjs/sinon#1338]
* Sinon version : 2.0.0
* Environment   : Windows 7 with phantomjs
* Example URL   :
* Other libraries you are using:

### 2.0.0-pre.4 code

```js
    const sandbox = sinon.sandbox.create();

    sandbox.stub(window, "innerWidth", width);
    sandbox.stub(window, "innerHeight", height);
    sandbox.stub(window, "matchMedia", (size) => {
        return {
            matches: size === mediaQuery.get(screenSize).query
        };
    });
```

**What did you expect to happen?**

To work. And it works with 2.0.0-pre.4 version.

### 2.x code as per migrating instructions 

```js
    const sandbox = sinon.sandbox.create();

    sandbox.stub(window, "innerWidth", width);
    sandbox.stub(window, "innerHeight", height);
    sandbox.stub(window, "matchMedia", (size) => {
        return {
            matches: size === mediaQuery.get(screenSize).query
        };
    });
```

**What did you expect to happen?**

it works.

**What actually happens**

but it gives me these warnings

Gives me these warnings: 

```sh
INFO: 'sinon.stub(obj, 'meth', fn) is deprecated and will be removed fromthe public API in a future version of sinon.
 Use stub(obj, 'meth').callsFake(fn).
 Codemod available at https://github.com/hurrymaplelad/sinon-codemod'
```

**Fixed using docs for stub**

```js
    const sandbox = sinon.sandbox.create();

    sandbox.stub(window, "innerWidth").returns(width);
   sandbox.stub(window, "innerHeight").returns(height);
   sandbox.stub(window, "matchMedia").callsFake((size) => {
        return {
            matches: size === mediaQuery.get(screenSize).query
        };
    });
```

**What actually happens**

I start getting errors

```sh
TypeError: sandbox.stub(...).returns is not a function
```

What am I doing wrong here? Thanks for help.

**Comment by zurfyx** [comment]
_Disclaimer: I don't know much about sinon 2, so excuse me if that's not what you're looking for. Tbh, I just started using it._

Why are you using `.returns`?

The warning clearly says: `Use stub(obj, 'meth').callsFake(fn).` (which basically implies moving your custom function from the third parameters to the `.callsFake`)

So, in your case, the translation would be:

```
sandbox.stub(window, "innerWidth").callsFake(width);
sandbox.stub(window, "innerHeight").callsFake(height);
sandbox.stub(window, "matchMedia").callsFake((size) => {
      return {
          matches: size === mediaQuery.get(screenSize).query
      };
  });
```

Btw, you can make your last one shorter:

```
(size) => ({
  matches: size === ...
});
```

**Comment by fatso83** [comment]
What you are doing is trying to define what properties will return when being accessed. The syntax for this changed to be more explicit in version 2. See the get and set methods for property accessors:
http://sinonjs.org/releases/v2.0.0/stubs/

**Comment by BenLorantfy** [comment]
This doesn't work for me. 
```
describe('test', () => {
  let sandbox;

  beforeEach(() => {
    sandbox = sinon.sandbox.create();
    sandbox.stub(window, "innerWidth").get(() => 1000);
    sandbox.stub(window, "innerHeight").get(() => 1000);
  })

  afterEach(() => {
    sandbox.restore();
  });

  it('should do a thing', () => {
    console.log(window.innerWidth); // 1024
    console.log(window.innerHeight); // 768
  });
});
```

```
 PASS  src/components/Tooltip/tests/index.test.js
  test
    ✓ should do a thing (2ms)

  console.log src/components/Tooltip/tests/index.test.js:58
    1024

  console.log src/components/Tooltip/tests/index.test.js:59
    768

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.573s, estimated 1s
```

**Comment by fatso83** [comment]
That should work, but even if Sinon gives you the possibility it doesn't mean the browser allows you to change browser native objects. `window` is very different from `{}`, so what works in Firefox might not work in Edge or Chrome.

Anyway, this isn't the place for usage questions. We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions.
