### ISSUE TITLE
Stubbing a property getter works, but stub.called remains false

### ISSUE THREAD

**Issue by OliverCole** [sinonjs/sinon#1545]
Stubbing a property getter works, but `stub.called` remains `false`.

* Sinon version : 3.2.1
* Environment   : Node 7
* Other libraries you are using: None

**What did you expect to happen?**
Getting a stubbed property should set `stub.called` to `true`.

**What actually happens**
`stub.called` remains `false`

**How to reproduce**
```javascript
var sinon = require('sinon');

var myObj = {
    prop: 'foo'
  };

var st = sinon.stub(myObj, 'prop').get(function getterFn() {
    return 'bar';
  });

console.log(myObj.prop);
console.log(st.called);
```

```
λ node testcase.js
bar
false
```

**Comment by fatso83** [comment]
This seems to have been like that forever. Not sure if this is a bug or not, as you are not actually calling the stub, but the getter set through the stub. And there are further complications, as you might see from this:
```javascript
sinon.stub(myObj, 'prop').get(getterFunction).set(setterFunction);
myObj.prop = 1;
myObj.prop;
myObj.prop = 2;
```
The stub now has two methods. How would we go about this when trying to count `callCount`, `called` and friends? Would you mean the stub has been called 1 time, 2 times or 3 times?

**Comment by fatso83** [comment]
I'll close this as a non-bug, but we could perhaps need to clarify this in the docs. Feel free to update them.

**Comment by OliverCole** [comment]
How would I mock/stub the value of the property, and check it was called?

**Comment by fatso83** [comment]
I am not sure if a "best" way, but one way (although inelegant) is to make the getter a stub too, and check on that. `getterFn=sinon.stub().returns('baz')`

**Comment by yongish** [comment]
Been trying many ways to stub a getter, but all approaches still lead to `createRPCThunk1.called` `false`.
`var sandbox = sinon.createSandbox(sinon.defaultConfig);`
`const createRPCThunk1 = sandbox.stub(webRpcRedux, 'createRPCThunk')`
`const createRPCThunk1 = sandbox.stub(webRpcRedux, 'createRPCThunk').callsFake(() => 'baz')`
`const createRPCThunk1 = sandbox.stub(webRpcRedux, 'createRPCThunk').returns('baz');`

**Comment by fatso83** [comment]
@yongish We are trying to keep the issue tracker focused on actual bugs. If you need help with something I suggest you try posting to StackOverflow (remember the `sinon` tag!) _with a good description of what you want to achieve_ (very hard to understand now). The issue tracker isn't a help forum, but some of us monitor the `sinon` tag on Stack Overflow and try to answer if we have time.

**Comment by jshado1** [comment]
For those trying to figure out how to do this, this thread hints at the solution:

```js
const obj = {
    get a() { },
    set a() { },
};

const getterSpy = sinon.spy();
const setterSpy = sinon.spy();

sinon.stub(obj, 'a')
    .get(getterSpy)
    .set(setterSpy);

getterSpy.calledOnce; // false
obj.a;
getterSpy.calledOnce; // true

setterSpy.calledOnce; // false
obj.a = 'foo';
setterSpy.calledOnce; // true
```

I haven't tried spying on both the getter and setter at the same time, but I know the above works individually.

**Comment by RoystonS** [comment]
That's interesting. Presumably you can use `sinon.stub()` instead of `spy` there too (as it's not really spying on anything: no original methods get run)?

(Thinking aloud...)

In fact, if you were to write
`const getterSpy = sinon.spy(obj, 'a')`, would you get a _real_ spy that actually spies on the original implementation?

**Comment by jshado1** [comment]
>if you were to write `const getterSpy = sinon.spy(obj, 'a')`

@RoystonS, you would get an error that obj.a is not a function.

**Comment by DanKaplanSES** [comment]
I think this might be officially documented now. Check the section named "[Using a spy to wrap property getter and setter](https://sinonjs.org/releases/v17/spies/)"

---

> @JakobJingleheimer 
> For those trying to figure out how to do this, this thread hints at the solution:
> 
> ```js
> ...
> sinon.stub(obj, 'a')
>     .get(getterSpy)
>     .set(setterSpy);
> 
> getterSpy.calledOnce; // false
> obj.a;
> getterSpy.calledOnce; // true
> 
> setterSpy.calledOnce; // false
> obj.a = 'foo';
> setterSpy.calledOnce; // true
> ```

Why doesn't this work when you give the stub a name and use it in your assertions instead? i.e.,:

```js
...
const stubProperty = sinon.stub(obj, 'a')
    .get(getterSpy)
    .set(setterSpy);

stubProperty.calledOnce; // false
obj.a;
stubProperty.calledOnce; // always false

stubProperty.calledOnce; // false
obj.a = 'foo';
stubProperty.calledOnce; // always false
```

It would make more sense to me if `stubProperty` had a callCount `> 1`, but it is always `0`. Why is that the case?

**Comment by JakobJingleheimer** [comment]
Um, it's been 6 years.

I presume the problem is how you're accessing it (indirectly instead of the spy/stub itself).

**Comment by DanKaplanSES** [comment]
> Um, it's been 6 years.
Sorry, I didn't communicate this well, but I was throwing that out into the ether for anyone to answer.

> I presume the problem is how you're accessing it (indirectly instead of the spy/stub itself).
I think so too. Maybe I'm mistaken, but with stubbed functions/methods, I don't recall this posing a problem; it feels like stubbing properties makes the sinon API work differently. 

Either way, I experimented a lot with your example and learned a lot in the process. I've expanded on it in [this StackOverflow post](https://stackoverflow.com/questions/78434094/in-sinon-how-do-you-assert-a-property-accessor-was-used-before-after-another-te).

**Comment by fatso83** [comment]
```javascript
const getterSpy = sinon.spy();
const setterSpy = sinon.spy();

const obj = {
    a: 42,
};

const stubProperty = sinon.stub(obj, "a").get(getterSpy).set(setterSpy);

const b = obj.a;
const c = obj.a;
obj.a = 43;

console.log(getterSpy.callCount); // 2
console.log(setterSpy.callCount); // 1
```
