### ISSUE TITLE
sinon.restore is deprecated and will be removed from the public API in a future version of sinon.

### ISSUE THREAD

**Issue by sweetim** [sinonjs/sinon#1390]
I am getting the warning above, after upgrading from Sinon v1.7 to Sinon v2.2

but, i check the document `sinon.restore` is not deprecated, any idea?

**Comment by mantoni** [comment]
Yes, it's missing in the docs. This is an internal utility function and was deprecated in Sinon `v2`.

**Comment by mantoni** [comment]
Fixed. It should show up in the migration guides deprecation list shortly.

**Comment by sweetim** [comment]
awesome! but how to migrate from using `sinon.restore` ? 
Just dont use it?

**Comment by mantoni** [comment]
You can call `restore` on stubs and sandbox instances. The global `sandbox.restore` was never meant to be used, but since it was there we had to introduce a deprecation warning before removing it entirely. It wasn't even documented in [the legacy docs](http://legacy.sinonjs.org/docs/).

**Comment by sweetim** [comment]
I created a sample migration code below, for anyone who has the same problem

```
// Previously
sinon.restore(stubObject);

// After for Typescript user
(stubObject as any).restore();

// After for Javascript user
stubObject.restore();
```

**Comment by davinci2015** [comment]
If I stub all the object’s methods like
`let stub = sinon.stub(obj);`
how can I restore stub after?
`stub.restore(); // TypeError: stub.restore is not a function`

**Comment by kopax** [comment]
@sweetim  I had this : 


```jsx
  afterEach(() => {
    clock = sinon.restore();
  });
```

I replaced as in your migration example : 

```jsx
  beforeEach(() => {
    clock = sinon.useFakeTimers();
  });
  afterEach(() => {
    clock.restore();
  });
```

I have now this error : 

```jsx
    TypeError: Cannot read property 'restore' of undefined
```

**Comment by fatso83** [comment]
@kopax we are trying to keep the issue tracker for bugs in the code. this seems like a usage question, in which case you could try our mailing list, Gitter or stackoverflow. Your code example works with Sinon 2.3 and Node 7.4, so your code must be doing something else (for instance restoring the clock before hitting the `afterEach`). Just tried this:

```javascript
> clock=sinon.useFakeTimers()
> Date.now()
0
> clock.restore()
> Date.now()
1496995253874
```

**Comment by kopax** [comment]
@fatso83 I use sinon `2.3.2` and node `7.10`.

**Comment by neetocode** [comment]
i have this code with error

```
AnyModel.findById = sinon.stub()

AnyModel.findById.resolves({})

AnyModel.restore() // TypeError: _models.AnyModel.findById.restore is not a function
```
AnyModel is a model by mongoosejs
i using sinon `2.4.1`

**Comment by davinci2015** [comment]
@neetocode 
You should stub _AnyModel.findById_ method like this:

`
const findByIdStub = sinon.stub(AnyModel, 'findById').resolves({})
`

**Comment by jackson-sandland** [comment]
This is still an issue. The warning indicates that use of .restore() is the better approach because of impending deprecation, but using .restore() results in `.restore is not a function` I'm using sinon 2.0.0

**Comment by fatso83** [comment]
@jackson-sandland, file an issue if there is something wrong in Sinon 4.x. It needs to include a snippet that shows what is wrong. Your "still a problem" for an issue that was about missing documentation for a deprecated method doesn't really say much.
